---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-service-secret
  namespace: library-prod
spec:
  encryptedData:
    JWT_SECRET: AgC97Tje7+Lyx/YLtWlhJKD/dxZ24uABEkqnfhDLI/oljpGiZ8d6mq+ekENJdM+18e+bpTLXaRu+E1og45lTPb4pMItILIDGwA2HRHiER1P6lcEWyQ2YHrUpiKPZcblr+9I26BY3bjLvHOT9qU7zGbDiKYMVV2bFWkg9lEhX74c+Bcw1vyckUCZYn01liCbRHu1LbRl3O5TD+V+Qlt3hT/XP9FbYz+nGD9X+Vh3sx8d0TtdN9vf2Y2mytWD75gCjYZjWd56X/agOF5MQWfiq320koHdDmxZoxpp8Ye+4POKPnHdyrq0x+1e9kLB++LBcySUq3dzGw2BU4RJLSzcN/pr6VqdO8kz8RH2E8eY2YKdjQcb+pfjiUgR+vRasXqdkWK02iL0hZV1yMMXKWegiEAGa4BeZUzuaiL+lklF21yqOHpd9G/y3a7HiXH0MAiixilg1LWQ7ZkOEPsJw/hrL+lz5K083Yr07DGZmgaAuDgqX0F4DSwoxvlHmHqHNX2KTTnPQxXC1MejIfIxLgqhDTTSKHi2oGzVRRJkS0YEU5+4kbXhjsG8RiC21y3FtKYMRrCPVJPzBPm75eSdgIGxyLcPHXYf7Y9qV6Bk5bRWlqLOpqnQrWtu3yy4usxgFhBeNWe02UyqSRCasGz4d6LxYNUP7g9czf3sHDr5a9stzD8SdBAOle/dJtUIsyPrWjHBX5OCKMSpDemIEMTvFdKPFywEaKv8A1LR4ZPQI7F8bZpGzzg5zro+EH1VVYpDVqQ==
  template:
    metadata:
      name: user-service-secret
      namespace: library-prod
    type: Opaque
