{{- $services := dict "book" .Values.bookService "user" .Values.userService "borrow" .Values.borrowService -}}
{{- range $name, $service := $services }}
{{- if $service.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "library-e2e.fullname" $ }}-{{ $name }}-hpa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "library-e2e.labels" $ | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "library-e2e.fullname" $ }}-{{ $name }}-service
  minReplicas: {{ $service.autoscaling.minReplicas }}
  maxReplicas: {{ $service.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $service.autoscaling.targetCPUUtilizationPercentage }}
---
{{- end }}
{{- end }}
