apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "library-e2e.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "library-e2e.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    app: mongodb
