apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mongodb.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.mongodb.name }}
data:
  MONGO_INITDB_DATABASE: "chapterone"
