{{- if .Values.borrowService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.borrowService.name }}-hpa
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.borrowService.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.borrowService.name }}
  minReplicas: {{ .Values.borrowService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.borrowService.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.borrowService.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
