apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: library-root-chart
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: library-e2e
    app.kubernetes.io/component: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: library-e2e
  source:
    repoURL: https://github.com/Googleeyy/ChapterOne-Helm.git
    targetRevision: dev
    path: .
    helm:
      releaseName: library-root
      valueFiles:
        - values-dev.yaml
      values: |
        book-service:
          name: book-service
          secretName: book-service-secret
          routePrefix: /api/books
          healthPath: /api/books
          image:
            repository: googleyy/chapterone-book
            tag: dev-bb5c906
            pullPolicy: IfNotPresent
          replicas: 1
          port: 8081
          database:
            name: chapterone_books_dev
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          autoscaling:
            enabled: false
        user-service:
          name: user-service
          secretName: user-service-secret
          routePrefix: /api/users
          healthPath: /actuator/health
          image:
            repository: googleyy/chapterone-user
            tag: dev-97a1bba
            pullPolicy: IfNotPresent
          replicas: 1
          port: 8082
          database:
            name: chapterone_users_dev
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          autoscaling:
            enabled: false
        borrow-service:
          name: borrow-service
          secretName: borrow-service-secret
          routePrefix: /api/borrows
          healthPath: /api-docs
          image:
            repository: googleyy/chapterone-borrow
            tag: dev-97e80d5
            pullPolicy: IfNotPresent
          replicas: 1
          port: 8083
          database:
            name: chapterone_borrows_dev
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          autoscaling:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: library-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
